set nocompatible            "do not use vi compatiblility mode

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General Settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

filetype on
filetype plugin on
filetype plugin indent on

syntax enable       " enable syntax highlighting

set ttyfast         " enable terminal acceleration

" Set colors & theme
"colorscheme monokain
set background=dark
set t_Co=256       "" TERM should be set correctly

set hidden          " dont cry if open another file without saving current changes

set ruler           " show current position
set number          " show line numbers

set cursorline      " highlight line under the cursor
set showmatch       " show matching part of bracket pairs
set nostartofline   " influences gg and GG cursor behaviour

set backspace=indent,eol,start  " backspace removes all (indents, EOLs, start)

set enc=utf-8	    " set default encoding

set nobackup 	    " no backup files
set nowritebackup   " disable if you want backups while writing
set noswapfile 	    " no swap files

set hlsearch        " enable highlight search
set termguicolors

"set wildmenu
"set showcmd

set cmdheight=2             " commandline height

"set notimeout ttimeout ttimeoutlen=200
"set timeoutlen=1000 ttimeoutlen=10

"set ignorecase
"set smartcase

"set confirm
"set visualbell
"set t_vb=

set scrolloff=10    " show N lines before/after cursor while scrolling

" Watch line too long!
"set colorcolumn=81
"execute "set colorcolumn=" . join(range(81,335), ',')
"highlight ColorColumn ctermbg=DarkGrey ctermfg=DarkRed

" ExtraWhitespace
highlight ExtraWhitespace ctermbg=red

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Load additional .vimrc files from workdir
"set exrc    " allow additional .vimrc files in current workdir
set secure  " prohibit .vimrc files to execute shell, create files, ...


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Clipboard settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" copy with \y or complete line with \yy per default
set clipboard=unnamedplus

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Keymappings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
nnoremap <C-L> :nohl<CR><C-L>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Mouse settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set mouse=a
let g:is_mouse_enabled = 1
noremap <silent> <Leader>m :call ToggleMouse()<CR>
function ToggleMouse()
    if g:is_mouse_enabled == 1
        echo "Mouse OFF"
        set mouse=
        let g:is_mouse_enabled = 0
    else
        echo "Mouse ON"
        set mouse=a
        let g:is_mouse_enabled = 1
    endif
endfunction

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" indentation
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set tabstop=4       " N whitespaces for tabs
set shiftwidth=4    " shift lines by N spaces
set smarttab        " set tabs for shifttabs logic
set expandtab       " expand tab into spaces
set autoindent      " automatical indent when moving to the next line

" Filetype-specific formatting
au FileType make set noexpandtab shiftwidth=4
au FileType vim setlocal foldmethod=marker

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Tabs / Buffers settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
tab sball
set switchbuf=useopen
set laststatus=2
nmap <F9> :bprev<CR>
nmap <F10> :bnext<CR>

