if type eza 2>&1 >/dev/null; then
  alias ls='eza'
  alias l='eza --group-directories-first'
  alias ll='eza -lg --group-directories-first'
  alias lg='eza -lg --group-directories-first --git'
  alias la='eza -lag --group-directories-first'
  alias lt='eza -Tg --git-ignore --level=2 --group-directories-first'
  alias llt='eza -lgT --git-ignore --level=2 --group-directories-first'
  alias lT='eza -Tg --git-ignore --level=4 --group-directories-first'
else
  alias l='ls -lah --group-directories-first'
  alias ll='ls -alF --group-directories-first'
  alias la='ls -A --group-directories-first'
fi

alias tmux='tmux -u'
alias vim='nvim'

# cd shorts
alias ..='cd ..'
alias ...='cd ../..'

jj() {
	command journalctl --no-pager $@ | ccze -A | less -R
}
