scan_timeout = 20

add_newline = false

[username]
disabled = false
style_user="cyan"
format = "[$user]($style)"
show_always = true

[hostname]
style="bold dimmed purple"
ssh_only = false
format =  "@[$hostname](bold red):"
trim_at = ""
disabled = false

[directory]
style = "bold blue"
truncation_length = 8
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[package]
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[rust]
format = "via [⚙️ $version](cyan bold)"
