---

- name: Create gnupg dir
  file:
    path: $HOME/.gnupg
    state: directory
    mode: '700'

- name: Configure gpg
  become: false
  template:
    src: templates/gpg.conf
    dest: $HOME/.gnupg/gpg.conf
    mode: '644'

- name: Configure gpg-agent
  become: false
  template:
    src: templates/gpg-agent.conf
    dest: $HOME/.gnupg/gpg-agent.conf
    mode: '644'

- name: Configure gpg-agent
  become_user: root
  become: true
  template:
    src: templates/gpg-agent.sh
    dest: /etc/profile.d/gpg-agent.sh
    mode: '644'