
[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#756565"
blue = "#6FC1FF"
cyan = "#67d3c2"
green = "#19f9d8"
magenta = "#FF9AC1"
red = "#FF2C6D"
white = "#ffffff"
yellow = "#ffcc95"

[colors.normal]
black = "#756565"
blue = "#45A9F9"
cyan = "#67d3c2"
green = "#19f9d8"
magenta = "#FF75B5"
red = "#FF2C6D"
white = "#E6E6E6"
yellow = "#FFB86C"

[colors.primary]
background = "#222222"
#background = "#292A2B"
foreground = "#D6D6D6"

[cursor]
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "Off"
shape = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
#family = "Fira Mono for Powerline"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
#family = "Fira Mono for Powerline"
style = "Medium"

[font.normal]
#family = "Fira Mono for Powerline"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = false

[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[general]
live_config_reload = false
