---

- name: Install base packages
  become: true
  become_user: root
  pacman:
    name:
      - alacritty
      - cmake
      - wget
      - curl
      - git
      - zsh
      - neovim
      - ctags
      - tmux
      - pcsc-tools
      # - xclip
      - wl-clipboard
      - starship
      - jq
      - powerline
      - awesome-terminal-fonts
      - powerline-fonts
      - noto-fonts-emoji
      - dust
      - eza
      - fd      # required for nvim
      - ripgrep
      # - zellij
    state: present
