---

- name: Configure vim
  become: no
  template:
    src: templates/vimrc
    dest: $HOME/.vimrc
    mode: '644'

- name: Create nvim dir
  file:
    path: $HOME/.config/nvim
    state: directory


