---

- name: Create directory
  become: false
  ansible.builtin.file:
    path: $HOME/.config/zellij
    mode: '0755'
    state: directory

- name: Configure zellij
  become: false
  template:
    src: templates/config.kdl
    dest: $HOME/.config/zellij/config.kdl
    mode: '644'
